databases:
  - name: travel_knock_db
    region: singapore
    plan: free
    databaseName: travel_knock_db
    user: travel_knock_user

services:
  - type: web
    name: travel_knock
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn TravelKnock.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: travel_knock_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true